FROM apache/airflow:2.10.5

USER airflow
RUN pip install --no-cache-dir openpyxl

# Pour d'autres dépendances, ajoute-les ici :
# RUN pip install --no-cache-dir openpyxl pandas snowflake-connector-python snowflake-sqlalchemy
